# Generated by Django 4.1.3 on 2023-08-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junkpile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appproject',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='appproject',
            name='project_url',
            field=models.URLField(blank=True),
        ),
    ]
